#!/bin/bash

yum install python-pip -y
pip install virtualenv
pip install --upgrade pip
pip install django psycopg2 


# setting up the django environment
mkdir /opt/myproject
virtualenv /opt/myproject/myprojectenv
source /opt/myproject/myprojectenv/bin/activate
django-admin.py startproject myproject /opt/myproject


sed -i '76,82 s/^/#/ ' /opt/myproject/myproject/settings.py
#No global (g)  required since this will be only done in these lines. 
#this finds this file and return the path to you.     ex. find / -name "settings.py" 


echo "DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'myproject',
        'USER': 'myprojectuser',
        'PASSWORD': 'password',
        'HOST': 'a.b.c.d',
        'PORT': '5432',
    }
}" >> /opt/myproject/myproject/settings.py
#change the PORT, NAME, HOST, PASSWORD
#PORT is 5432, HOST is the internal ip of your server 

# migrate before creating a superuser
python /opt/django/manage.py migrate
# deletes and creates the superuser
echo "from django.contrib.auth.models import User; User.objects.filter(email='root@example.com').delete(); User.objects.create_superuser('root', 'root@example.com', 'password123')" | python /opt/django/manage.py shell
 
# run the following as 'codes'
sudo -u root -E sh -c "\\
source /opt/django/bin/activate && \\
/opt/django/manage.py runserver 0:8000 &"




echo "[nti-320]
name=Extra Packages for Centos from NTI-320 7 - $basearch
#this will create a .repo file inside this server that will point to the repository server.
baseurl=http://5.6.7.8/CentOS/7/Packages/
enabled=1
gpgcheck=0
" >> /etc/yum.repos.d/NTI-320.repo



#http://server_domain_or_IP:8000 --> how to view if it worked
# these commands are just for visual effect  (yum install tree -y)--> (tree myproject) 

