#!/bin/bash
yum install epel-release -y 
yum install python-pip -y
pip install virtualenv
pip install --upgrade pip

#setting up the django environment
mkdir /opt/django
virtualenv /opt/django/djangoenv
source /opt/django/djangoenv/bin/activate

pip install django psycopg2
django-admin startproject myproject /opt/django


#sed -i '76,82 s/^/#/ ' /opt/django/myproject/settings.py
#No global (g)  required since this will be only done in these lines. 
#this finds this file and return the path to you.     ex. find / -name "settings.py" 

yum -y install wget
wget https://github.com/carlosaguilar1928/NTI320-FINAL/blob/master/settings.py
mv settings.py to /opt/django/myproject/settings.py
#echo "DATABASES = {
#    'default': {
 #       'ENGINE': 'django.db.backends.postgresql_psycopg2',
  #      'NAME': 'myproject',
   #     'USER': 'myprojectuser',
    #    'PASSWORD': 'Password',
     #   'HOST': '10.142.0.2',
      #  'PORT': '5432',
#    }
#}" >> /opt/django/myproject/settings.py
#change the PORT, NAME, HOST, PASSWORD
#PORT is 5432, HOST is the internal ip of your server 

# migrate before creating a superuser
python /opt/django/manage.py migrate
# deletes and creates the superuser
echo "from django.contrib.auth.models import User; User.objects.filter(email='root@example.com').delete(); User.objects.create_superuser('root', 'root@example.com', 'password123')" | python /opt/django/manage.py shell
 
# run the following as 'root'

source /opt/django/djangoenv/bin/activate 
/opt/django/manage.py runserver 0.0.0.0:8000 &



# this is the echo for the REPO server RPM 
echo "[nti-320]
name=Extra Packages for Centos from NTI-320 7 - $basearch
#this will create a .repo file inside this server that will point to the repository server.
baseurl=http://5.6.7.8/CentOS/7/Packages/
enabled=1
gpgcheck=0
" >> /etc/yum.repos.d/NTI-320.repo

#http://server_domain_or_IP:8000 --> how to view if it worked
# these commands are just for visual effect  (yum install tree -y)--> (tree myproject) 
#1.	Simple install virtual environment and python version
#2.	use virtualenv env to create virtualenvironment.
#3.	activate your virtualenv. using . /env_name/bin/activate
#4.	use pip install django==1.70 (specify version to install django)
#5.	pip list to list all installed packages

