#!/bin/bash

#first of all install the ldap client on the nfsclient machine
export DEBIAN_FRONTEND=noninteractive
apt-get install -y libpam-ldap nscd 
# install the debconf-utils GUI 
wget https://raw.githubusercontent.com/carlosaguilar1928/Monitoring-/master/ldap_debconf
# wget the raw ldap_debconf configuration files that were extrapolated from the manual configuration
while read line; do echo "$line" | debconf-set-selections; done < ldap_debconf
sed -i 's/compat/compat ldap/g' /etc/nsswitch.conf 
/etc/init.d/nscd restart
sed -i 's,uri ldapi:///,uri ldap://a.b.c.d,g' /etc/ldap.conf
sed -i 's/base dc=example,dc=net/base dc=nti310,dc=local/g' /etc/ldap.conf
export DEBIAN_FRONTEND=interactive
# this variable turns on/off the "ncurses" GUI from debconf

apt-get install -y nfs-client
# install the nfs client in our machine

showmount -e $1.2.3.4
#shows us where the available mounts on our remote server are
#after the $ sign, insert the internal ip of our nfs server 

mkdir /mnt/test
#make a mount point for the 'test' nfs share

echo "1.2.3.4:/var/nfsshare/testing	/mnt/test	nfs	defaults 0 0" >> /etc/fstab
# when you are done , echo your mount/share configuration into the fstab file
# this will mount the share on reboot; you should use your nfs server ip address not 1.2.3.4

mount -a
#execute this command to mount all the shares in your fstab file


#test by changing direcotory into the /mnt/test directory and su'ing one of your ldap users
# after su'ing the user perform and ls and notice that the user is the owner of the file
# also the ldap group you added that user to, should be the owner of the group
cd /mnt/test 
su bob
ls -l 
