#!/bin/bash


echo "#########installing apache, phpldapadmin, openldap######" 
yum -y install httpd
yum -y install epel-release
yum -y install phpldapadmin
yum install -y openldap-servers openldap-clients        #installs ldap 

#turn off selinux becasue it messes with apache
sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config 

#enable and restart apache
systemctl enable httpd
systemctl start httpd

echo "installing the php config file here" 
yum install wget -y
wget https://raw.githubusercontent.com/carlosaguilar1928/NTI320-FINAL/master/config.php
cp /home/carlosaguilar1928/config.php /etc/phpldapadmin/
# allow ldap access thru the web gui
sed -i 's/Allow from 127.0.0.1/Allow from all/g' /etc/httpd/conf.d/phpldapadmin.conf
sed -i 's,Require local,#Require local\n   Require all granted,g' /etc/httpd/conf.d/phpldapadmin.conf 

# change ownership of the config php file
chown ldap:apache /etc/phpldapadmin/config.php
systemctl restart httpd



echo "#######configuring ldap and ldapadmin########"

# mess with password credentials for your ldap server 
newsecret=$(slappasswd -g)
newhash=$(slappasswd -s "$newsecret")
echo -n "$newsecret" > /root/ldap_admin_pass
chmod 0600 /root/ldap_admin_pass

# insert schema information into ldif file
echo -e "dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcSuffix
olcSuffix: dc=nti310,dc=local
\n
dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcRootDN
olcRootDN: cn=ldapadm,dc=nti310,dc=local
\n
dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcRootPW
olcRootPW: $newhash" > db.ldif

# modify schema of ldap in db.ldif
ldapmodify -Y EXTERNAL -H ldapi:/// -f db.ldif

# install ssl certificate
echo "dn: olcDatabase={1}monitor,cn=config
changetype: modify
replace: olcAccess
olcAccess: {0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external, cn=auth" read by dn.base="cn=ldapadm,dc=nti310,dc=local""

ldapmodify -Y EXTERNAL -H ldapi:/// -f monitor.ldif

#this creates the ssl certificate
open ssl req -new -x509 -nodes -out /etc/openldap/certs/nti310ldapcert.pem -keyout /etc/openldap/certs/nti310ldapkey.pem -days 365 -subj "/C=US/ST=WA/L=Seattle/O=SCC/OU=IT/CN=nti310.local"

chown -R ldap. /etc/openldap/certs/nti*.pem

echo -e "dn: cn=config
changetype: modify
replace: olcTLSCertificateFile
olcTLSCertificateFile: /etc/openldap/certs/nti310ldapcert.pem
\n
dn: cn=config
changetype: modify
replace: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: /etc/openldap/certs/nti310ldapkey.pem" > certs.ldif
# vim to certs.ldif and enter spaces after each "dn" 

ldapmodify -Y EXTERNAL -H ldapi:/// -f certs.ldif

ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/shema/inetorgperson.ldif

echo -e "dn: dc=nti310,dc=local
dc: nti310
objectClass: top
objectClass: domain
\n
dn: cn=ldapadm ,dc=nti310,dc=local
objectClass: organizationalRole
cn: ldapadm
description: LDAP Manager
\n
dn: ou=People,dc=nti310,dc=local
objectClass: organizationalUnit
ou: People
\n
dn: ou=Group,dc=nti310,dc=local
objectClass: organizationalUnit
ou: Group" > base.ldif
# vim to this file and add spaces after each dn

ldapadd -x -W -D "cn=ldapadm,dc=nti310,dc=local" -f base.ldif -y /root/ldap_admin_pass


#echo "[nti-320]
#name=Extra Packages for Centos from NTI-320 7 - $basearch
#this will create a .repo file inside this server that will point to the repository server.
#baseurl=http://5.6.7.8/CentOS/7/Packages/
#enabled=1
#gpgcheck=0
#" >> /etc/yum.repos.d/NTI-320.repo


# web interface ipaddress/phpldapadmin
# password is stored in /root/ldap_admin_pass
