#!/bin/bash

# generate  an ssl certificate
mkdir /root/SSL/mail.mydomain.com -p
cd /root/SSL/mail.mydomain.com
openssl req -nodes -x509 -newkey rsa:2048 -keyout mail.mydomain.com.key -out mail.mydomain.com.crt -days 365

# Move ssl certificate to /ect/ssl
cp mail.mydomain.com.key mail.mydomain.com.crt /etc/ssl/

# install exim
yum install -y exim mailx
cp /etc/exim/exim.conf{,.orig}

# edit the exim.conf
# vim /etc/exim/exim.conf

sed -i 's/primary_hostname =/primary_hostname = mail.mydomain.com/g' /etc/exim/exim.conf
sed -i 's/domainlist local_domains = @ : localhost : localhost.localdomain/domainlist local_domains = @ : mydomain.com/g' /etc/exim/exim.conf
sed -i 's;tls_certificate = /etc/pki/tls/certs/exim.pem;tls_certificate = /etc/ssl/mail.mydomain.com.crt;g' /etc/exim/exim.conf
sed -i 's;tls_privatekey = /etc/pki/tls/private/exim.pem;tls_privatekey = /etc/ssl/mail.mydomain.com.key;g' /etc/exim/exim.conf
sed -i 's/auth_advertise_hosts =/auth_advertise_hosts = */g' /etc/exim/exim.conf

#edit the transport section on /etc/exim/exim.conf

sed -i '873,880 s/^/#/ ' /etc/exim/exim.conf

echo "local_delivery:
  driver = appendfile
  directory = $home/Maildir
  maildir_format
  maildir_use_size_file
  delivery_date_add
  envelope_to_add
  return_path_add" >> /etc/exim/exim.conf
  
  
systemctl start exim
systemctl enable exim
systemctl status exim
