#!/bin/bash

gcloud init
1
intense-reason-191902

echo "#######creating firewall rules########"

gcloud compute firewall-rules create allow-http --description " allow http." \
    --allow tcp:80
gcloud compute firewall-rules create allow-https --description "Allow https." \
    --allow tcp:443
gcloud compute firewall-rules create allow-nrpe --description "Allow nrpe-server communication." \
    --allow tcp:5666
gcloud compute firewall-rules create allow-ldap --description "Allow ldap allowed." \
    --allow tcp:636
gcloud compute firewall-rules create allow-postgresql --description "Allow Postgresql." \
    --allow tcp:5432
gcloud compute firewall-rules create allow-django --description "Django test server connection allowed." \
    --allow tcp:8000

echo "#######Installing git###########"

yum install git -y    
git clone https://github.com/carlosaguilar1928/NTI320-FINAL
 
 
echo "########Deployments#############" 

gcloud compute instances create ldap-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro  --metadata-from-file startup-script=/home/carlosaguilar1928/NTI320-FINAL/ldap-server 
gcloud compute instances create nfs-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro  --metadata-from-file startup-script=/home/carlosaguilar1928/NTI320-FINAL/nfs-server
sleep 5

echo "Resolving Dependencies LDAP" 
    #ldapip=(gcloud compute instances list | grep ldapserver)
    #echo $ldapid
ldapip=$(gcloud compute instances list | grep ldap-server  | awk '{print $4}')
sed -i "s/a.b.c.d/$ldapip/g" /home/carlosaguilar1928/nfs-client-auto
nfsip=$(gcloud compute instances list | grep nfs-server  | awk '{print $4}')
sed -i "s/1.2.3.4/$nfsip/g" /home/carlosaguilar1928/nfs-client-auto
sleep 2

echo "launching nfs and ldap client"
gcloud compute instances create client-01 --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/carlosaguilar1928/NTI320-FINAL/nfs-client-auto 
  
echo "launching postgres" 
gcloud compute instances create postgresql-db --image-family centos-7 --image-project centos-cloud --machine-type f1-micro  --metadata-from-file startup-script=/home/carlosaguilar1928/NTI320-FINAL/postgresql

echo "resolving dependencies for django"  
postgresip=$(gcloud compute instances list | grep posgressql-db  | awk '{print $4}')
sed -i "s/a.b.c.d/$postgresip/g" /home/carlosaguilar1928/NTI320-FINAL/django-for-postgress
sleep 3
echo "launching django" 
gcloud compute instances create django-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro  --metadata-from-file startup-script=/home/carlosaguilar1928/NTI320-FINAL/django-server

echo "launching mail server" 
gcloud compute instances create mail-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro  --metadata-from-file startup-script=/home/carlosaguilar1928/NTI320-FINAL/mail-server

Echo "launching monitoring servers!!!!"
echo "launching nagios" 
gcloud compute instances create nagios-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro  --metadata-from-file startup-script=/home/carlosaguilar1928/NTI320-FINAL/nagios-server

echo "launching cacti"
gcloud compute instances create cacti-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro  --metadata-from-file startup-script=/home/carlosaguilar1928/NTI320-FINAL/cacti-server

echo "launching rsyslog"
gcloud compute instances create rsyslog-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro  --metadata-from-file startup-script=/home/carlosaguilar1928/NTI320-FINAL/rsyslog-server


echo "######### Building RPM###########"
gcloud compute scp nti-320.spec carlosaguilar1928@10.142.0.x:/rpmbuild/SPECS
gcloud compute scp sample.gz carlosaguilar1928@10.142.0.x:/rpmbuild/SOURCES
sleep 3
gcloud compute ssh carlosaguilar1928@10.142.0.x --command "cd /rpmbuild && rpmbuild -v -bb --clean SPECS/nti-320"


echo "########## Transfer RPM to REPO and work with repo############"
echo "launching repo server"
gcloud compute instances create repo-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro  --metadata-from-file startup-script=/home/carlosaguilar1928/NTI320-FINAL/repository-server
sleep 5
gcloud compute scp --recurse Build-server:/rpmbuild/RPMS/rpmfile.rpm /carlosaguilar1928
gcloud compute scp /carlosaguilar1928/rpmfile.rpm carlosaguilar1928@repo-server:/repos/CenOS/7/Packages


echo "######### Install RPM in all clients ############" 
for servers in $(gcloud compute instances list | awk 'NR >= 2{ print$1 }');
do 
  gcloud compute ssh carlosaguilar1928@$servers --command "yum install -y rpmfile.rpm";  
done  

echo "######### Generate Nagios check files ###########" 





