#!/bin/bash

yum install -y nfs-utils
#installs nfs-utils for our server

# create a directory structure called /nfsshare
mkdir /var/nfsshare
mkdir /var/nfsshare/devstuff
mkdir /var/nfsshare/testing
mkdir /var/nfsshare/home_dirs

#change permissions to all open, for testing purposes
chmod -R 777 /var/nfsshare/

# enable a number of nfs services 
systemctl enable rpcbind
systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmap

#start a number of nfs services
systemctl start rpcbind
systemctl start nfs-server
systemctl start nfs-lock
systemctl start nfs-idmap

#rpcbind is not strictly necessary for nfs4 

#change directory to our share directory
cd /var/nfsshare

# list the share we are going to export and put them into /etc/exports
echo "/var/nfsshare/home_dirs *(rw.sync,no_all_squash)
/var/nfsshare/devstuff *(rw.sync,no_all_squash)
var/nfsshare/testing *(rw.sync,no_all_squash)" >> /etc/exports

# after changing the configuration restart the nfs server
systemctl restart nfs-server

#install the net-tools so we can use ifconfig
yum install -y net-tools

echo "[nti-320]
name=Extra Packages for Centos from NTI-320 7 - $basearch
#this will create a .repo file inside this server that will point to the repository server.
baseurl=http://5.6.7.8/CentOS/7/Packages/
enabled=1
gpgcheck=0
" >> /etc/yum.repos.d/NTI-320.repo

# $ip needs to be replaced with the actual number and the name and location neet to match
