#!/bin/bash 

yum install epel-release -y
yum install python-pip python-devel gcc postgresql-server postgresql-devel postgresql-contrib -y
postgresql-setup initdb
#yum install -y httpd

# enable and start postgressql and httpd
systemctl enable postgresql
systemctl start postgresql
systemctl enable httpd 
systemctl start httpd


# su - postgres
# this will enter you into the postgres mode, we comment out the "su -postgress" command due to it being done automatically in the below echo statment
#psql
# this will enter you into the "$postgress mode",we comment out the "psql" command due to it being done automatically in the below echo statment

#create the settings via an echo line instead of manually
echo -e "CREATE DATABASE myproject;
\n
CREATE USER myprojectuser WITH PASSWORD 'Password';
\n
ALTER ROLE myprojectuser SET client_encoding TO 'utf8';
\n
ALTER ROLE myprojectuser SET default_transaction_isolation TO 'read committed';
\n
ALTER ROLE myprojectuser SET timezone TO 'UTC';
\n
ALTER USER postgres WITH PASSWORD 'Password';
GRANT ALL PRIVILEGES ON DATABASE myproject TO myprojectuser;" > /tmp/sqlfile.sql

# this line changes user to "postgres"
sudo -i -u postgres psql -U postgres -f /tmp/sqlfile.sql  

# Now install a web-based GUI to view our database 
yum install -y phpPgAdmin 
sed -i 's/Require local/Require all granted/g' /etc/httpd/conf.d/phpPgAdmin.conf
sed -i 's/Allow from 127.0.0.1/Allow from all/g' /etc/httpd/conf.d/phpPgAdmin.conf
sed -i 's/$conf\['\''extra_login_security'\''\] = true;/$conf\['\''extra_login_security'\''\] = false;/g' /etc/phpPgAdmin/config.inc.php

# set permissions
sed -i 's/local   all             all                                     peer/local   all             all                                     md5/g' /var/lib/pgsql/data/pg_hba.conf

sed -i 's|host    all             all             127.0.0.1/32            md5|host    all             all             all            md5|g' /var/lib/pgsql/data/pg_hba.conf

sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /var/lib/pgsql/data/postgresql.conf

sed -i 's/#port/port/g' /var/lib/pgsql/data/postgresql.conf

sed -i 's/ident/md5/g' /var/lib/pgsql/data/pg_hba.conf



setenforce 0
systemctl restart postgresql
systemctl restart httpd


#test with (tail -F /var/log/messages | grep startup); (systemctl status postgresql)
#login ipaddress/phpPgAdmin  
#username:postgres  password:Password
