#!/bin/bash

#install the rpm packages
yum -y install rpm-build make gcc git 
yum install nfs-utils -y
#create an envioronement for the RPM creation
mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

#get files and copy them to appropiate location 
yum install -y wget 
wget https://raw.githubusercontent.com/carlosaguilar1928/NTI320-FINAL/master/sample.spec 
cp /sample.spec /root/rpmbuild/SPECS

wget https://github.com/nic-instruction/hello-nti-320/blob/master/startup-0.1.tar.gz?raw=true
mv startup-0.1.tar.gz\?raw\=true startup-0.1.tar.gz
cp /startup-0.1.tar.gz /root/rpmbuild/SOURCES

#change directory and run the rpmcommand
cd /root/rpmbuild
rpmbuild -v -bb --clean SPECS/sample.spec

# create and mount NFS directory with NFS server IP using sed
mkdir /mnt/nfs
echo "1.2.3.4:/var/nfsshare/home_dirs  /mnt/nfs  nfs     defaults 0 0" >> /etc/fstab
mount -a

# change file to your network mount to be view via the network
cp /root/rpmbuild/RPMS/x86_64/*.rpm /mnt/nfs
