#!/bin/bash

#install the rpm packages
sudo yum -y install rpm-build

#create an envioronement for the RPM creation
mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

#get files and copy them to appropiate location 
yum install -y wget 
wget https://raw.githubusercontent.com/carlosaguilar1928/NTI320-FINAL/master/sample.spec 
cp /home/carlosaguilar1928/sample.spec /root/rpmbuild/SPECS

#wget 
#cp 

#change directory and run the rpmcommand
cd /rpmbuild
rpmbuild -v -bb --clean SPECS/nti-320"

# create and mount NFS directory with NFS server IP using sed
mkdir /mnt/nfs
echo "1.2.3.4:/var/nfsshare/home_dirs  /mnt/nfs  nfs     defaults 0 0" >> /etc/fstab
mount -a

# change file to your network mount to be view via the network
cp /rpmbuild/BUILD/file.rpm /mnt/nfs
