#!/bin/bash         

   #uncomment these 4 lines in the /etc/rsyslog.conf file  to open tcp and udp ports
   # vi /etc/rsyslog.conf 
   
#$ModLoad imudp
#$UDPServerRun 514
    # Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514

sed -i "s/#\$ModLoad imudp/\$ModLoad imudp/g" /etc/rsyslog.conf
sed -i "s/#\$UDPServerRun 514/\$UDPServerRun 514/g" /etc/rsyslog.conf
sed -i "s/#\$ModLoad imtcp/\$ModLoad imtcp/g" /etc/rsyslog.conf
sed -i "s/#\$InputTCPServerRun 514/\$InputTCPServerRun 514/g" /etc/rsyslog.conf

# to escape a $ you must place a \ behind it. ex--> \$


systemctl restart rsyslog.service
yum install net-tools
netstat -antup | grep 514                # make sure service is listening
                                         # still need to secure log server
                                         # port 514 is the designated port for rsyslog
                                         
                                         
                                      
                                      
 
